### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index -1

### ISSUE THREAD

**Issue by Xitee1** [Xitee1/PowerBoard#25]
Reported by @lukriq on Discord:

```
[20:18:51 WARN]: [PowerBoard] Plugin PowerBoard v3.5.15 generated an exception while executing task 1421
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
        at java.util.ArrayList.add(ArrayList.java:455) ~[?:?]
        at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
        at de.xite.scoreboard.modules.ranks.RankManager.delay(RankManager.java:246) ~[PowerBoard.jar:?]
        at de.xite.scoreboard.modules.ranks.RankManager.setTablistRanks(RankManager.java:106) ~[PowerBoard.jar:?]
        at de.xite.scoreboard.modules.ranks.RankManager.register(RankManager.java:28) ~[PowerBoard.jar:?]
        at de.xite.scoreboard.modules.ranks.RankManager.updateTablistRanks(RankManager.java:169) ~[PowerBoard.jar:?]
        at de.xite.scoreboard.depend.LuckPermsListener$1.run(LuckPermsListener.java:33) ~[PowerBoard.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-225]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-225]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:18:51 WARN]: [PowerBoard] Plugin PowerBoard v3.5.15 generated an exception while executing task 1422
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
        at java.util.ArrayList.fastRemove(ArrayList.java:642) ~[?:?]
        at java.util.ArrayList.remove(ArrayList.java:629) ~[?:?]
        at de.xite.scoreboard.modules.ranks.RankManager.delay(RankManager.java:245) ~[PowerBoard.jar:?]
        at de.xite.scoreboard.modules.ranks.RankManager.setTablistRanks(RankManager.java:106) ~[PowerBoard.jar:?]
        at de.xite.scoreboard.modules.ranks.RankManager.register(RankManager.java:28) ~[PowerBoard.jar:?]
        at de.xite.scoreboard.modules.ranks.RankManager.updateTablistRanks(RankManager.java:169) ~[PowerBoard.jar:?]
        at de.xite.scoreboard.depend.LuckPermsListener$1.run(LuckPermsListener.java:33) ~[PowerBoard.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-225]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-225]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by GammaPotato** [comment]
when will this be fixed? As a result, I am missing the prefix in Tab

**Comment by GitReboot** [comment]
Any solution to this?

**Comment by Xitee1** [comment]
No sorry. I'm no longer developing on this project.

**Comment by MrClean1337** [comment]
> No sorry. I'm no longer developing on this project.

Will you ever develop on this project again?

**Comment by Xitee1** [comment]
Probably not. I only maintain it a bit if someone else might wants to contribute. But so far there were no PRs.

**Comment by itsTyrion** [comment]
I'm facing an issue on my network and I want to add a thing or two anyway so I might just do that 👀
