### ISSUE TITLE
[Bug?] Lag on Gamemode change.

### ISSUE THREAD

**Issue by spikehidden** [Xitee1/PowerBoard#5]
When I change the gamemode from creative to spectator Powerboard seems to cause a lot of lag and also sometimes show this warning in the log:

```log
[02:00:39 WARN]: [PowerBoard] Plugin PowerBoard v3.5.10 generated an exception while executing task 66
java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_18_R2.scoreboard.CraftObjective.checkState(CraftObjective.java:159) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scoreboard.CraftObjective.setDisplayName(CraftObjective.java:59) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at de.xite.scoreboard.modules.board.ScoreTitleUtils.setTitle(ScoreTitleUtils.java:26) ~[PowerBoard.jar:?]
        at de.xite.scoreboard.modules.board.ScoreboardManager$1.run(ScoreboardManager.java:146) ~[PowerBoard.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

To check what caused the lag I run the `timings` command. The results can be found here:
https://timings.aikar.co/?id=8f7406c8cc5e4564b01c351fe1776f9e

**Comment by Xitee1** [comment]
I sadly could not reproduce the problem.
If I change my game mode there is no lag at all, even if I change it really fast.
Can you please attach your PowerBoard folder so I can test it with your config?

But you can try the attached PowerBoard jar or build it yourself with the new commits I have just pushed. It executes the scoreboard update Asynchronously. But that's only a workaround because it still needs ressources, but in another task, so it does not block the main server task,
[PowerBoard.zip](https://github.com/Xitee1/PowerBoard/files/8984451/PowerBoard.zip)
